language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - python setup.py clean
  - python setup.py build
  - coverage run --source=unihandecode setup.py test

after_success:
  - coveralls

deploy:
  - provider: pypi
    user: miurahr
    password:
      secure: Cnx2TnF4OdTQbdcNFbf3YUqpthSoXIgdiAJFqtUhBvKzr3PR+bAqifynQk1Nk66veyiWyYTojVJM3Mmysl+IozsM5mVGjVkxOh91oi/fqIL4Pr/YEHlcs1/av6yKOp/YxPvg1fH3zhaM7B6lJc+9ofHh0Paohy5z7AO3yXtHaEY=
    distributions: bdist_wheel
    skip_existing: true
    on:
      repo: miurahr/unihandecode
      python: '3.6'
      tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/54e31f6a06c65d0620ca
    on_success: change
    on_failure: always
    on_start: neve
