language: python
python: 3.3
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34

before_install:
  - sudo apt-get update
  - sudo apt-get install python3.4 python3.4-dev

install:
  - pip install tox
  - pip install -r requirements.txt -r requirements-dev.txt --use-mirrors
# command to run tests
script: tox
