language: python
python: 3.4
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34

before_install:
  - sudo apt-get update
  - sudo apt-get install make

install:
  - pip install tox
  - pip install -r requirements.txt -r requirements-dev.txt

script: tox
